import { Poppins } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import SidebarWrapper from "@/Components/sidebar-wrapper"; // ADD THIS
import '@ant-design/v5-patch-for-react-19'; // Fix antd v5 compatibility with React 19

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-[#1E113B]`}>
        <NextTopLoader
          showSpinner={false}
          height={3}
          crawlSpeed={200}
          speed={400}
          zIndex={9999}
        />

        <div className="flex">
          <main className="flex-1">{children}</main>
        </div>

        <div className="bg-wrapper fixed bottom-0 left-0 opacity-[0.35] z-[-1]">
          <img src="/assets/Landing/bg-main.svg" alt="background-image" />
        </div>
      </body>
    </html>
  );
}
